EmprestimosWall/Models/EmprestimosModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace EmprestimosWall.Models
{
    public class EmprestimosModel
    {
        public int Id { get; set; }
        
        [Required(ErrorMessage ="Por favor, informe o nome do recebedor!")]
        public string Recebedor { get; set; }

        [Required(ErrorMessage = "Por favor, informe o nome do fornecedor!")]
        public string Fornecedor { get; set; }

        [Required(ErrorMessage = "Por favor, informe o nome do Livro!")]
        public string LivroEmprestado { get; set; }
        public DateTime DataEmprestimo { get; set; } 

    }

 }

EmprestimosWall/Models/ErrorViewModel.cs
namespace EmprestimosWall.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmprestimosWall/Models/ResponseModel.cs
namespace EmprestimosWall.Models
{
    public class ResponseModel<T>
    {
        private T? Dados { get; set; }
        public string Mensagem { get; set; } = string.Empty;
        public bool status { get; set; } = true;
    }
}

EmprestimosWall/Models/UsuarioModel.cs
namespace EmprestimosWall.Models
{
    public class UsuarioModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string Email { get; set; }
        public byte[] SenhaHash { get; set; }
        public byte[] SenhaSalt { get; set; }
    }
}

EmprestimosWall/Controllers/EmprestimoController.cs
using ClosedXML.Excel;
using EmprestimosWall.Data;
using EmprestimosWall.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace EmprestimosWall.Controllers
{

    public class EmprestimoController : Controller
    {

        readonly private ApplicationDbContext _context;

        public EmprestimoController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<EmprestimosModel> emprestimos = _context.Emprestimos;
            return View(emprestimos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {

            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimosModel emprestimo = _context.Emprestimos.FirstOrDefault(x => x.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimosModel emprestimo = _context.Emprestimos.FirstOrDefault(x => x.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Exportar()
        { 
            var dados = GetDados();

            using (XLWorkbook workbook = new XLWorkbook())
            {
                workbook.AddWorksheet(dados, "Dados Emprestimo");

                using MemoryStream ms = new MemoryStream();
                {
                    workbook.SaveAs(ms);
                    return File(ms.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Emprestimo.Xls");
                       
                }
            }
            return Ok(); 
        }
            
        private DataTable GetDados()
        {
            
            DataTable dataTable = new DataTable();

            dataTable.TableName = "Dados emprestimo";

            dataTable.Columns.Add("Recebedor", typeof(string));
            dataTable.Columns.Add("Fornecedor", typeof(string));
            dataTable.Columns.Add("Livro", typeof(string));
            dataTable.Columns.Add("Data Emprestimo", typeof(DateTime));

            var dados = _context.Emprestimos.ToList();

            if(dados.Count > 0)
            {
                dados.ForEach(empretimo =>
                { dataTable.Rows.Add(empretimo.Recebedor, empretimo.Fornecedor, empretimo.LivroEmprestado, empretimo.DataEmprestimo); });

            }
            return dataTable;
        }

        [HttpPost]
        public IActionResult Cadastrar(EmprestimosModel emprestimos)
        {
            if (ModelState.IsValid)
            {
                _context.Emprestimos.Add(emprestimos);
                _context.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";

                return RedirectToAction("Index");
            }
            return View();

        }

        [HttpPost]

        public IActionResult Editar(EmprestimosModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                var emprestimoDb = _context.Emprestimos.Find(emprestimo.Id);

                emprestimoDb.Fornecedor = emprestimo.Fornecedor;
                emprestimoDb.Recebedor = emprestimo.Recebedor;
                emprestimo.LivroEmprestado = emprestimo.LivroEmprestado;


                _context.Emprestimos.Update(emprestimoDb);
                _context.SaveChanges();

                TempData["MensagemSucesso"] = "Edição realizado com sucesso!";

                return RedirectToAction("Index");
            }
            
            return View(emprestimo);
        }

        [HttpPost]

        public IActionResult Excluir(EmprestimosModel emprestimo)
        {
            if (emprestimo == null)
            {
                return NotFound();
            }

            _context.Emprestimos.Remove(emprestimo);
            _context.SaveChanges();

            TempData["MensagemSucesso"] = "Remoção realizada com sucesso!";

            return RedirectToAction("Index");
        }
    }
}

EmprestimosWall/Controllers/HomeController.cs
using EmprestimosWall.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimosWall.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmprestimosWall/Controllers/LoginController.cs
using EmprestimosWall.Dto;
using EmprestimosWall.Services.LoginService;
using Microsoft.AspNetCore.Mvc;

namespace EmprestimosWall.Controllers
{
    public class LoginController : Controller
    {
        public readonly ILoginService _LoginService;

        public LoginController(ILoginService loginService)
        {
            _LoginService = loginService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registrar(UsuarioRegisterDto usuarioRegisterDto)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _LoginService.RegistrarUsuario(usuarioRegisterDto);

                if (usuario.status)
                {
                    TempData["MenssagemSucesso"] = usuario.Mensagem;
                }
                else
                {
                    TempData["ErroMenssagem"] = usuario.Mensagem;
                    return View(usuarioRegisterDto);
                }
                return RedirectToAction("index");
            }
            else {
                return View(usuarioRegisterDto);
            }
        }
    }
}

EmprestimosWall/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimosModel

@{
    ViewData["title"] = "Cadastrar emprestimo";
}
<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de emprestimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control text-light " asp-for="Recebedor" id="Recebedor" placeholder =" Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light ">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder=" Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light ">Livro</label>
            <input type="text" class="form-control text-light " asp-for="LivroEmprestado" id="Livro" placeholder=" Qual livro está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Adicionar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>



    </form>
</div>

EmprestimosWall/Views/Emprestimo/Editar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Editar emprestimo";
}
<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de emprestimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Editar">
        <input type="hidden" asp-for="Id" />

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder=" Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder=" Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual livro está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>



    </form>
</div>

EmprestimosWall/Views/Emprestimo/Excluir.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Excluir emprestimo";
}
<div class="container bg-dark p-5 rounded-5">

    <div class="mb-5 text-center">
        <h1 class="text-light">Exclusão de emprestimos</h1>
    </div>

    <form method="post" asp-controller="Emprestimo" asp-action="Excluir">
        <input type="hidden" asp-for="Id" />

        <h2 class="text-light">Tem certeza que deseja excluir o registro?</h2>

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor:</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?" disabled>
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?" disabled>
            <span class="text-danger" asp-validation-for="Fornecedor"></span>
        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual livro está sendo emprestado?" disabled>
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>



    </form>
</div>

EmprestimosWall/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimosModel>
<div class="Contanier">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Emprestimos</h1>
        <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Exportar"> <i class="bi bi-file-earmark-plus mx-1"></i>Exportar</a>
        <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar"> <i class="bi bi-file-earmark-plus mx-1"></i>Cadastrar novo emprestimo</a>
    </div>


    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-light" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }
   

<table id="Emprestimos" class="table table-light table-hover mt-5">
    <thead>
        <tr>
            <th scope="col">Recebedor</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Livro</th>
            <th scope="col">Data Emprestimo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @if(Model != null)
        {
            @foreach(var emprestimo in Model)
            {
                <tr>
                    <th scope="row">@emprestimo.Recebedor</th>
                    <td>@emprestimo.Fornecedor</td>
                    <td>@emprestimo.LivroEmprestado</td>
                    <td>@emprestimo.DataEmprestimo</td>
                    <td>
                            <a asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" class="btn btn-warning mx-2"><i class="bi bi-pencil-square mx-1 "></i>Editar</a>
                            <a asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill mx-1"></i>Excluir</a>
                    </td>
                </tr>
            }
        } 

    </tbody>
</table>

</div>

EmprestimosWall/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Empréstimo de livros online</h1>

    <p>"Ao ter acesso a novos livros, as pessoas podem ser incentivadas a ler, expandindo seu universo de conhecimento e lazer."</p>
    <div>
        <img src="/img/conhecimento.png"/>
    </div>
</div>

EmprestimosWall/Views/Login/Index.cshtml
@if (TempData["MenssagemSucesso"] != null)
{
    <div class="alert alert-success text-light" role="alert">
        @TempData["MenssagemSucesso"]
    </div>
}
@if (TempData["ErroMenssagem"] != null)
{
    <div class="alert alert-success text-light" role="alert">
        @TempData["ErroMenssagem"]
    </div>
}

<div class="container bg-light  p-5 rounded-5">
    <form>
        <div class="form-group">
            <label for="Email">Email:</label>
            <input type="email" class="form-control" id="Email1">
        </div>
        <div class="form-group">
            <label for="senha">Senha:</label>
            <input type="password" class="form-control" id="Senha">
        </div>

        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-primary w-25 mx-2">Entrar</button>
            <a class="btn w-25 "asp-controller="Login" asp-action="Registrar">Cadastra-se</a>
        </div>

    </form>
</div>

EmprestimosWall/Views/Login/Registrar.cshtml
@using EmprestimosWall.Dto
@model UsuarioRegisterDto

<h1>Cadastro de Usuários</h1>

@if (TempData["MenssagemSucesso"] != null)
{
    <div class="alert alert-success text-light" role="alert">
        @TempData["MenssagemSucesso"]
    </div>
}
@if (TempData["ErroMenssagem"] != null)
{
    <div class="alert alert-danger text-light" role="alert">
        @TempData["ErroMenssagem"]
    </div>
}

<div asp-validation-summary="All" class="text-danger"></div>

<div class="container bg-light p-5 rounded-5">
    <form asp-action="Registrar" aps-asp-controller="Login" method="post" >
        <div class="form-group">
            <label for="Email">Email:</label>
            <input type="email" class="form-control" id="Email" name="Email" asp-for="Email">
        </div>

        <div class="form-group">
            <label for="Nome">Nome:</label>
            <input type="text" class="form-control" id="Nome" name="Nome" asp-for="Nome">
        </div>

        <div class="form-group">
            <label for="Sobrenome">Sobrenome:</label>
            <input type="text" class="form-control" id="Sobrenome" name="Sobrenome" asp-for="Sobrenome">
        </div>

        <div class="form-group">
            <label for="Senha">Senha:</label>
            <input type="password" class="form-control" id="Senha" name="Senha" asp-for="Senha">
        </div>

        <div class="form-group">
            <label for="ConfirmarSenha">Confirme a senha:</label>
            <input type="password" class="form-control" id="ConfirmarSenha" name="ConfirmarSenha">
        </div>

        <div class="d-flex justify-content-center mt-4">
            <button type="submit" class="btn btn-primary w-25 mx-2">Cadastrar</button>
            <a class="btn btn-secondary w-25" asp-controller="Login" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

EmprestimosWall/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Emprestimos de livros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Materia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/fix.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimosWall.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-2.3.1/datatables.min.css" rel="stylesheet"integrity="sha384-euvbLDizNhjdB+SK/Ai+GY3WCCHaDJM1tnnh2IqvUY9zjhlo21JkywSg8X5hlMY8" crossorigin="anonymous">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">BookLoan</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home<i class="mx-2 bi bi-house-fill"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimo" asp-action="Index">Emprestimos<i class="mx-2 bi bi-book"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Index">Login<i class="mx-2 bi bi-door-closed"></i></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2025 - BookLoan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.3.1/datatables.min.js" integrity="sha384-1LmfH5u7+DRwux/q4YYqAi+OjwkIVYJdPQijPS9S28cj8AeFnpNCkSVlZgvRdOzb" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>